# Generated by Django 3.2.8 on 2021-10-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('occupied', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='musonge/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
